# Generated by Django 5.2.17 on 2026-09-30 17:14

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_chapter_name_ci')],
            },
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male')], max_length=10)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentors', to='registration.chapter')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_sub', models.CharField(max_length=64, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='registration.chapter')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SignupSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spreadsheet_id', models.CharField(max_length=128)),
                ('spreadsheet_title', models.CharField(max_length=200)),
                ('tab_id', models.BigIntegerField()),
                ('tab_title', models.CharField(max_length=200)),
                ('field_map', models.JSONField(default=dict)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('synced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='registration.chapter')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='SeatingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tables', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('excluded_mentors', models.ManyToManyField(blank=True, related_name='+', to='registration.mentor')),
                ('sheet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='registration.signupsheet')),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_key', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=200)),
                ('nickname', models.CharField(blank=True, max_length=120)),
                ('gender', models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male')], max_length=10)),
                ('level', models.CharField(blank=True, choices=[('undergrad', 'Undergrad'), ('grad', 'Grad')], max_length=10)),
                ('status', models.CharField(choices=[('not_contacted', 'Not contacted'), ('awaiting_response', 'Awaiting response'), ('confirmed', 'Confirmed'), ('no_response', 'No response'), ('not_inviting', 'Not inviting')], default='not_contacted', max_length=20)),
                ('door_gender', models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male')], max_length=10)),
                ('door_level', models.CharField(blank=True, choices=[('undergrad', 'Undergrad'), ('grad', 'Grad')], max_length=10)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='registration.signupsheet')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('sheet', 'row_key'), name='unique_row_per_sheet')],
            },
        ),
    ]
