# Generated by Django 5.2.17 on 2026-09-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_more_contact_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='door_level',
            field=models.CharField(blank=True, choices=[('undergrad', 'Undergrad'), ('grad', 'Grad'), ('other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='signup',
            name='level',
            field=models.CharField(blank=True, choices=[('undergrad', 'Undergrad'), ('grad', 'Grad'), ('other', 'Other')], max_length=10),
        ),
    ]
