# Generated by Django 5.2.17 on 2026-09-30 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_enrollment_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupsheet',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
