# Generated by Django 5.2.17 on 2026-09-30 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_sheet_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupsheet',
            name='warnings',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
