# Generated by Django 5.2.17 on 2026-09-30 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_sheet_warnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='waitlisted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
