# Generated by Django 5.2.17 on 2026-09-30 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_signup_waitlisted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupsheet',
            name='reserved_released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signupsheet',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
