# Generated by Django 5.2.17 on 2026-10-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_sheet_start_and_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='status',
            field=models.CharField(choices=[('not_contacted', 'Not contacted'), ('waiting_to_contact', 'Waiting to contact'), ('awaiting_response', 'Awaiting response'), ('confirmed', 'Confirmed'), ('no_response', 'No response'), ('not_coming', 'Not coming'), ('no_room', 'No room'), ('no_space', 'No space'), ('not_inviting', 'Not inviting')], default='not_contacted', max_length=20),
        ),
    ]
