# Generated by Django 5.2.17 on 2026-10-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0008_no_space_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="signupsheet",
            name="rows_read_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
