# Generated by Django 5.2.17 on 2026-10-09 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0009_sheet_rows_read_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="signupsheet",
            name="event_name",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
